sudo: false
dist: trusty
language: cpp

matrix:
  include:

    - os: linux
      env:
        - COMPILER=gcc-4.9 
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - libfreetype6-dev
            - libpng++-dev
            - zlib1g-dev
            - libunittest++-dev
            - libfontconfig1-dev

    - os: linux
      env:
        - COMPILER=gcc-4.9 
        - CXXFLAGS="-D_GLIBCXX_DEBUG"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - libfreetype6-dev
            - libpng++-dev
            - zlib1g-dev
            - libunittest++-dev
            - libfontconfig1-dev

    - os: linux
      env:
        - COMPILER=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libfreetype6-dev
            - libpng++-dev
            - zlib1g-dev
            - libunittest++-dev
            - libfontconfig1-dev

    - os: linux
      env:
        - COMPILER=gcc-7
        - CXXFLAGS="-D_GLIBCXX_DEBUG"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libfreetype6-dev
            - libpng++-dev
            - zlib1g-dev
            - libunittest++-dev
            - libfontconfig1-dev

    - os: osx
      env:
        - COMPILER=clang 
      install:
        - brew install unittest-cpp

script:
  - export CC=$COMPILER
  - export CXX=${CC/gcc/g++}
  - export CXX=${CXX/clang/clang++}
  - $CXX --version
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - ./bin/testlib; if [ $? -ne 0 ]; then ./bin/testlib -v; exit 1; fi
